language: c
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
before_install:
  - pip install --user cpp-coveralls
install:
  - wget http://www.mega-nerd.com/libsndfile/files/libsndfile-1.0.26.tar.gz
  - tar -xzvf libsndfile-1.0.26.tar.gz
  - cd libsndfile-1.0.26.tar.gz && ./configure && make && make check && sudo make install
script:
  - make && make tests && env LD_LIBRARY_PATH=./ ./test
after_success:
  - coveralls --gcov-options '\-lp'
